---

- name: NGINX Ingress Controller | Create addon dir
  file:
    path: "{{ kube_config_dir }}/addons/ingress_nginx"
    state: directory
    owner: root
    group: root
    mode: 0755
  when:
    - inventory_hostname == groups['kube-master'][0]

- name: NGINX Ingress Controller | Templates list
  set_fact:
    ingress_nginx_templates:
      - { name: namespace, file: namespace.yml, type: ns }
      - { name: sa-ingress-nginx, file: sa-ingress-nginx.yml, type: sa }
      - { name: sa-ingress-nginx-admission, file: sa-ingress-nginx-admission.yml, type: sa }
      - { name: role-ingress-nginx, file: role-ingress-nginx.yml, type: role }
      - { name: role-ingress-nginx-admission, file: role-ingress-nginx-admission.yml, type: role }
      - { name: clusterrole-ingress-nginx, file: clusterrole-ingress-nginx.yml, type: clusterrole }
      - { name: clusterrole-ingress-nginx-admission, file: clusterrole-ingress-nginx-admission.yml, type: clusterrole }
      - { name: rolebinding-ingress-nginx, file: rolebinding-ingress-nginx.yml, type: rolebinding }
      - { name: rolebinding-ingress-nginx-admission, file: rolebinding-ingress-nginx-admission.yml, type: rolebinding }
      - { name: clusterrolebinding-ingress-nginx, file: clusterrolebinding-ingress-nginx.yml, type: clusterrolebinding }
      - { name: clusterrolebinding-ingress-nginx-admission, file: clusterrolebinding-ingress-nginx-admission.yml, type: clusterrolebinding }
      - { name: cm-ingress-nginx, file: cm-ingress-nginx.yml, type: cm }
      - { name: svc-ingress-nginx-controller, file: svc-ingress-nginx-controller.yml, type: svc }
      - { name: svc-ingress-nginx-controller-admission, file: svc-ingress-nginx-controller-admission.yml, type: svc }
      - { name: deploy-ingress-nginx-controller, file: deploy-ingress-nginx-controller.yml, type: deploy }
      - { name: job-ingress-nginx-controller-admission-create, file: job-ingress-nginx-controller-admission-create.yml, type: job }
      - { name: job-ingress-nginx-controller-admission-patch, file: job-ingress-nginx-controller-admission-patch.yml, type: job }
      - { name: ingressclass, file: ingressclass.yml, type: ingressclass }
      - { name: validationwebhood, file: validationwebhood.yml, type: validationwebhood }

- name: NGINX Ingress Controller | Create manifests
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ kube_config_dir }}/addons/ingress_nginx/{{ item.file }}"
  with_items: "{{ ingress_nginx_templates }}"
  register: ingress_nginx_manifests
  when:
    - inventory_hostname == groups['kube-master'][0]

- name: NGINX Ingress Controller | Apply manifests
  kube:
    name: "{{ item.item.name }}"
    namespace: "{{ ingress_nginx_namespace }}"
    kubectl: "{{ bin_dir }}/kubectl"
    resource: "{{ item.item.type }}"
    filename: "{{ kube_config_dir }}/addons/ingress_nginx/{{ item.item.file }}"
    state: "latest"
  with_items: "{{ ingress_nginx_manifests.results }}"
  when:
    - inventory_hostname == groups['kube-master'][0]
